### ISSUE TITLE
ctail does not behave when log-lines are piped in

### ISSUE THREAD

**Issue by codemedic** [raducotescu/ctail#2]
It does not seem to function when piping in log.

```
ssh host.somewhere.com tail -f /var/log/some-app.log | ctail
```

That doesn't seem to work at all. It is handy to have this feature, so that the `ctail` script does not have to be copied on to hosts.

**Comment by codemedic** [comment]
@raducotescu I was thinking of splitting the colourising logic into its own script called `tinge`

Rationale; the fix for this issue really is to just execute the awk script (see my commit) when data comes from stdin, at which point it is not really `tail`ing anymore.

PS: `tinge`?! I hear you ask; to avoid any language partiality `colourise` v/s `colorize`, and it means "to slightly colour" something

**Comment by raducotescu** [comment]
@codemedic, three years later I get to see this issue (really really sorry...).

Are you still interested in merging your contribution?

**Comment by codemedic** [comment]
Yes please

**Comment by raducotescu** [comment]
Can you please send a PR with your changes? I can then then verify it and merge it. 😁

**Comment by codemedic** [comment]
Sorry! Just noticed. It is already merged. I will close this now.
https://github.com/raducotescu/ctail/commit/f9762dc281743a79f44e4c4cffbfb948b9cb50f3
